// generated by stringer -type=State; DO NOT EDIT

package battery

import "fmt"

const _State_name = "ChargingDischargingEmptyFullyChargedPendingDischarge"

var _State_index = [...]uint8{0, 8, 19, 24, 36, 52}

func (i State) String() string {
	i -= 1
	if i < 0 || i >= State(len(_State_index)-1) {
		return fmt.Sprintf("State(%d)", i+1)
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
